version = 5.8.0
archive_dir = /config/etc/letsencrypt/archive/dnhpg.kitek-pg.ru
cert = /config/etc/letsencrypt/live/dnhpg.kitek-pg.ru/cert.pem
privkey = /config/etc/letsencrypt/live/dnhpg.kitek-pg.ru/privkey.pem
chain = /config/etc/letsencrypt/live/dnhpg.kitek-pg.ru/chain.pem
fullchain = /config/etc/letsencrypt/live/dnhpg.kitek-pg.ru/fullchain.pem
[renewalparams]
account = 2a327724beebef62fb61781bfec796eb
pref_challs = http-01,
config_dir = /config/etc/letsencrypt
work_dir = /tmp/letsencrypt
logs_dir = /config/log/letsencrypt
server = https://acme-v02.api.letsencrypt.org/directory
authenticator = standalone
key_type = ecdsa
[acme_renewal_info]
ari_retry_after = 2026-09-29T18:32:20
